CREATE TABLE OAUTH2_REGISTERED_CLIENT (
  ID VARCHAR(100) NOT NULL,
  CLIENT_ID VARCHAR(100) NOT NULL,
  CLIENT_ID_ISSUED_AT TIMESTAMP NOT NULL,
  CLIENT_SECRET VARCHAR(150) NOT NULL,
  CLIENT_NAME VARCHAR(100) NOT NULL,
  TOKEN_SETTINGS VARCHAR(255)
);

ALTER TABLE OAUTH2_REGISTERED_CLIENT
  ADD CONSTRAINT PK_OAUTH2_REGISTERED_CLIENT PRIMARY KEY (ID);

ALTER TABLE OAUTH2_REGISTERED_CLIENT
  ADD CONSTRAINT UNQ1_OAUTH2_REGISTERED_CLIENT UNIQUE (CLIENT_ID);
