CREATE TABLE OAUTH2_REGISTERED_CLIENT (
	ID TEXT(100) PRIMARY KEY NOT NULL,
	CLIENT_ID TEXT(100) UNIQUE NOT NULL,
	CLIENT_ID_ISSUED_AT INTEGER NOT NULL,
	CLIENT_SECRET TEXT(150) NOT NULL,
	CLIENT_NAME TEXT(100) NOT NULL,
	TOKEN_SETTINGS TEXT(255)
);

CREATE TABLE OAUTH2_AUTHORIZATION (
	ID INTEGER PRIMARY KEY NOT NULL,
	REGISTERED_CLIENT_ID TEXT(100) NOT NULL,
	PRINCIPAL_NAME TEXT(100) NOT NULL,
	ACCESS_TOKEN_ISSUED_AT INTEGER NOT NULL,
	ACCESS_TOKEN_EXPIRES_AT INTEGER NOT NULL,
	ACCESS_TOKEN_TYPE TEXT(50) NOT NULL,
	ACCESS_TOKEN_VALUE TEXT NOT NULL,
	FOREIGN KEY(REGISTERED_CLIENT_ID) REFERENCES OAUTH2_REGISTERED_CLIENT(ID)
);