CREATE TABLE OAUTH2_REGISTERED_CLIENT (
	ID TEXT(100) PRIMARY KEY NOT NULL,
	CLIENT_ID TEXT(100) UNIQUE NOT NULL,
	CLIENT_ID_ISSUED_AT INTEGER NOT NULL,
	CLIENT_SECRET TEXT(150) NOT NULL,
	CLIENT_NAME TEXT(100) NOT NULL,
	TOKEN_SETTINGS TEXT(255)
);